version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  setup-and-test:
    executor:
      name: node/default
    working_directory: ~/rasa-ui/packages/hs-react-ui
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm run test-react
            - run: npm run build-react
            - run: npm run build-docs
            - store_artifacts:
                path: coverage

workflows:
  PR-Merge:
    jobs:
      - setup-and-test:
